/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ViewRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const ViewRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : ViewRequestStatus,
  'presentationId' : IDL.Text,
  'guestName' : IDL.Text,
  'guestEmail' : IDL.Text,
  'requestedAt' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Presentation = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'ownerId' : IDL.Principal,
  'file' : ExternalBlob,
  'description' : IDL.Text,
  'uploadedAt' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveRequest' : IDL.Func([IDL.Text], [ViewRequest], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateQrCodeUrl' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getAllPresentations' : IDL.Func([], [IDL.Vec(Presentation)], ['query']),
  'getAllRequests' : IDL.Func([], [IDL.Vec(ViewRequest)], ['query']),
  'getApprovedPresentation' : IDL.Func([IDL.Text], [ExternalBlob], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPresentation' : IDL.Func([IDL.Text], [Presentation], ['query']),
  'getRequest' : IDL.Func([IDL.Text], [ViewRequest], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectRequest' : IDL.Func([IDL.Text], [ViewRequest], []),
  'submitViewRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [ViewRequest],
      [],
    ),
  'uploadPresentation' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [Presentation],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ViewRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const ViewRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : ViewRequestStatus,
    'presentationId' : IDL.Text,
    'guestName' : IDL.Text,
    'guestEmail' : IDL.Text,
    'requestedAt' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Presentation = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'ownerId' : IDL.Principal,
    'file' : ExternalBlob,
    'description' : IDL.Text,
    'uploadedAt' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveRequest' : IDL.Func([IDL.Text], [ViewRequest], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateQrCodeUrl' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getAllPresentations' : IDL.Func([], [IDL.Vec(Presentation)], ['query']),
    'getAllRequests' : IDL.Func([], [IDL.Vec(ViewRequest)], ['query']),
    'getApprovedPresentation' : IDL.Func([IDL.Text], [ExternalBlob], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPresentation' : IDL.Func([IDL.Text], [Presentation], ['query']),
    'getRequest' : IDL.Func([IDL.Text], [ViewRequest], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectRequest' : IDL.Func([IDL.Text], [ViewRequest], []),
    'submitViewRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [ViewRequest],
        [],
      ),
    'uploadPresentation' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [Presentation],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };