/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Presentation {
  'id' : string,
  'title' : string,
  'ownerId' : Principal,
  'file' : ExternalBlob,
  'description' : string,
  'uploadedAt' : Time,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface ViewRequest {
  'id' : string,
  'status' : ViewRequestStatus,
  'presentationId' : string,
  'guestName' : string,
  'guestEmail' : string,
  'requestedAt' : Time,
}
export type ViewRequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveRequest' : ActorMethod<[string], ViewRequest>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateQrCodeUrl' : ActorMethod<[string], string>,
  'getAllPresentations' : ActorMethod<[], Array<Presentation>>,
  'getAllRequests' : ActorMethod<[], Array<ViewRequest>>,
  'getApprovedPresentation' : ActorMethod<[string], ExternalBlob>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPresentation' : ActorMethod<[string], Presentation>,
  'getRequest' : ActorMethod<[string], ViewRequest>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectRequest' : ActorMethod<[string], ViewRequest>,
  'submitViewRequest' : ActorMethod<[string, string, string], ViewRequest>,
  'uploadPresentation' : ActorMethod<
    [string, string, ExternalBlob],
    Presentation
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];